language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: BE3UfKPXG5Klj6QOF89XL2lLTvHlgWebcLBdB2M4IlPDeVKzkdRWSF75NNs/4XzH0jI4gVOfrgaIo1n8L9LEY3kUCNtaM7HiSdzlfgDpE8iKMjXGYqlugaLntdf165Rt1DOFBZQ8QSxFEBtEueDqoj9RUCBcWC4eiRq06TIVsBaoBW3fqjV/rZ73tqZbnkx0fsxi/EIZjWFwcvnY8BQrvz4XwMNEeYvFuj++j4IMdW21UseCNypDOsVao08eHHguXepzVK7jSMcvbtNVX1yEBMNmlwgW2411Sv9lHfId0I7XP3jCSA3Eisk/3mA5KP6f3oGIu93WUEQ/lNhdTy1u1ulovExYMFvsqBc3pS5/KPRdUJr6XPY2fCWVd890zA8FR9FNFMDvfBIt5+fTLK/EDQriRocFppAuCbEPjLC3CHSCx4FldUB5i8HqbhQEBvpcBWDpyXUtFYuDo6Hxy0vOzQp0TFY9du3gRKBfpGqHJt0KsAJNCSBlg4Rkibb/vi5VRW6iglEocS+3ld4yGOMyO6eenjT7TK4U6nrdE6x/fTqaEzktqpIj+0jzEeaw/lz1EUczqKZ2KwbqwBTIbOjlyEz0a/vhH3jN1MciYVFs7klx6nxL4Wsxk2tSb3epCurO+Q0vEh+tp+n/WJ6XZT3e/pX8+bICZFHMlodehLmrPJo=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
before_script:
- npm run lint
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
