language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: "CbQMKPAQQSnEpq3zd9UkeBN/m7BPQZ9JjRL3kgrBg16cKERYUP68hHcQszd6ZprxSiGeXEwJG93yMKbhTXhPEwHGO5W5pHLKCRIJcjxNZgE9MndmMHphhk8cY8/O0U3pWQcDw0BT9S6OxAvGQpRhLST3rHGsybkKs/DMIQuA8QbyOTaxsnd+D5hvDV3nk2EUSmBnV0DdmY4NPVTPk0FiPm3Dbopxxf+PlbH45jawv7h0CGYOSvnCAGKao2Ttgqm2483KbmBpfmNv16MXQRUXoHdfJjTV7J1J3pBDrI+FhAYJ+cZL0Ci2r5Snv1qU8buVzuWSVF6R9We6OHbySfbM7IEn2Fw3PUKqKP/reh9Dul6be9bqnfwRXycET5+tzSKwLybhYHdOVzm8OpLBzDRXvKAU4qO6fkghqj/xt0h6x0GpWOTolRneUDRWrc87VBctyzhyzhi6dR49VaMpslefRGSM+UQb3a41nh4N1rZbk9QJbciWwYgyLBycj22KfJQ2Dz/EtRbGCHrAETj49VEWXeAepDDjBjHZG5C1pDkksZVd0x4G/mpYj1u/p9l9/qCWqfndtoCBnBmQ+TX03ODS6agOKvTfRBMlHp0+7PHNhvKsnVZcPEo3cwDzhl4BOxjWrv+1+y23km5OlZJMF56PRASxMRSPybZKJcSCB18i4IU="
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
before_script:
- npm run lint
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
