language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - STAGING_BRANCH=develop
  - secure: "iaRuFRNL7QZdctU2Ur/yt/sgceRNY49+fN7E30KfZQ5sXk0yUkZx9pBXk3LL+bFRTLLgaWnLGhduxN8qW+mRzxKRehah/iZidn6hfm8ZavaA6jit31MgIsXjhdFhbGiOQ2ewy/O3kyAdb11bjKlviMygYpRzJ2arpI9MhKZT8zy5UJq4FytbA7WQpesBIzW54LQkS10hr+n8hM3BRm8mneradeT4hdnovj9cfyn0qJtxNSvEGmVzu2Vl70dP4XivNCD2241Iy8nJvES6eZ5vrAd//kh09NlJ9rnJH/Le1xCpsGXXT4PraiCcaU7by4+dR3i5RSTCr4v4sw2VBrKC5QNa2AU4c0fhR03l92F+N+PdRWM9kcuJHJgnwBiZ6WjM0SOGkjfDLlbGAX3UIN0skhrEwqRMox7ENz9CzPk0nUcoE6bARYc0InIRJuVy/DmT4m9rsrGyvQksTDRxSJ+TZLQOy+k7QiTdHsMX1Ry6R1axU9rHwy49Wa/GMKCS4vEn4BQ3hA554F/KFmxSgg6YcA8ze2TyYCDavL/8LkoyzZ34KYh64bLshKHcLFfTmZnHfeVhH3z+X9jrtfRyvDbIJw/5Q6uJsSNIWni/rHCCT4QvLC0smFKb5fcvMjevoDXFNtscwPzNZgmFM3xa5Mlzvu9Cmv2snWOVRY78qLB5A+M="
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/build.sh
before_script:
- npm run lint
- npm test
script:
- ".build_scripts/build.sh"
deploy:
  - provider: script
    skip_cleanup: true
    script: ".build_scripts/deploy.sh"
    on:
      branch: "${DEPLOY_BRANCH}"
  - provider: s3
    access_key_id: AKIAI64NYOAFFWZEKWEA
    secret_access_key:
      secure: "e8NqZ5lce/e8IJC2cE0Gk3XkI9vQJLcDuGo5KCRo4kUq/h2aJ7mUHIkxBuMB/vtgDNJ5zRKjjWpOGHseOwcpEKuYyIPnM+axlhQtaxKE5lzzu00Z4/flWJdwNTxoMX+DFfkSK1Yvul46557usDyWkILngz6DDF/YdsBJQIomFs4hOczZzDcLl74hUEa+DwCn6J6nkzcJwtlXKV5ry+5gs0Oa3/CjN2TE9I9uc7E9GTvVJMShbnqAvKX+L5WEbYdWLrQiWCyU1FDaqjRVbQ9SDj95JqTzQ51GuoKvZEDcXQljB9s/Sm10lHTFhB84x+HToOBq5baZ+affjcLBFp8YHBiZUHwoirnOSBK13uS78Dl5HwHu5YMw+WBAqJ8Svkokff4JiR6k3v0VihChoTV/89cRuAdlN1l74wu4LvoxrX6B+mipFPsbTM5vfF5Pxxa+gd5cJ8hGuHenQ3kN7zqQUYAeFLKJQsrI8Sj47RZUYW4DUBiFrYQn+9AmnoXVgc+/MEXQYFA8qXHBFu0XVrAqSTUtyC62YeNLB9x+dVKfGNsnb7cmac7cuOnWIuE7em3OAix7xV2b8r5QFG4sR3Mq2DavC7+zlIjuxWe9td+PdkFll3vwvtMMQNVdizN3PCqBNjMQMeYCTFZpNK13UiSRdPoOc+HFa4U9+nmIkEYwNUo="
    bucket: hotosm-oam-uploader-staging
    region: us-east-1
    skip_cleanup: true
    local_dir: dist
    acl: public_read
    on:
      repo: hotosm/oam-uploader
      branch: "${STAGING_BRANCH}"