language: node_js
node_js:
  - "0.12"

env:
  global:
  - GH_REF=github.com/hotosm/oam-uploader.git
  - DEPLOY_BRANCH=master
  - secure: 

cache:
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh

script:
- npm run build

after_success:
- ./.build_scripts/deploy.sh
